language: objective-c
osx_image: xcode7.2
xcode_project: SampleTravisCi.xcodeproj
xcode_scheme: SampleTravisCi

xcodebuild test -project "SampleTravisCi.xcodeproj" -scheme "SampleTravisCi"
  -sdk "iphonesimulator"
  -destination "platform=iOS Simulator,OS=9.2,name=iPhone 6"

